### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nivedvenugopalan** [nivedvenugopalan/SRG-Analytics#2]
- [ ] Add Multi-Processing during Harvesting
- [ ] Stop Words Implementation
- [ ] Spam Channel Filter
- [ ] Channel Based
- [ ] Per User Graphs and Word clouds
- [ ] Word Usage

**Comment by nivedvenugopalan** [comment]
- [ ] Time Based Commands/ Info

**Comment by nivedvenugopalan** [comment]
- [ ] Rank in Profile
- [ ] Level System
- [ ] Command for Detailed Word Analysis

**Comment by MuhdRayan10** [comment]
- [ ] Word Cloud
- [ ] Visual Representation for Top X command

**Comment by nivedvenugopalan** [comment]
- [ ] Emoji Analytics

**Comment by MuhdRayan10** [comment]
- [ ] Individual User Word Cloud
- [ ] User Profile Comparison
